-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.registrations
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    tournament_id uuid,
    submitted_data jsonb NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    registered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT registrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tournaments
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    game_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    game_logo_url text COLLATE pg_catalog."default",
    banner_url text COLLATE pg_catalog."default" NOT NULL,
    participation_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    max_participants integer NOT NULL,
    min_team_size integer,
    max_team_size integer,
    registration_open_at timestamp with time zone NOT NULL,
    registration_close_at timestamp with time zone NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default",
    use_external_link boolean DEFAULT false,
    external_registration_url text COLLATE pg_catalog."default",
    form_schema jsonb DEFAULT '[]'::jsonb,
    created_by uuid,
    approved_by uuid,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    approved_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tournaments_pkey PRIMARY KEY (id),
    CONSTRAINT tournaments_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'ctv'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.registrations
    ADD CONSTRAINT registrations_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournaments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tournaments
    ADD CONSTRAINT tournaments_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tournaments_created_by
    ON public.tournaments(created_by);

END;