-- Legacy migration reference.
-- DUT and free participant accounts are now stored in public.participants.
-- Keep this file as a marker so old deployment notes do not reintroduce
-- student-specific columns on public.users.
